name: Update Submodules

on:
  schedule:
    # Run every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'

      - name: Update submodule
        run: |
          # Initialize submodule
          git submodule init
          git submodule update
          
          # Go to submodule directory
          cd kernel_platform/KernelSU-Next
          
          # Add verbose output for debugging
          echo "Remote repositories:"
          git remote -v
          
          # Force fetch the very latest from remote
          git fetch --force --prune origin
          
          # Display all branches to confirm what we're seeing
          echo "Available branches:"
          git branch -a
          
          # Hard reset to origin/next to force getting the latest
          git checkout -B next --track origin/next
          git reset --hard origin/next
          
          # Verify we have the latest commit
          echo "Current commit:"
          git rev-parse HEAD
          git log -1 --pretty=format:"%h %s"
          
          # Return to parent repository
          cd ../..
          
          echo "Submodule status:"
          git submodule status

      - name: Check for changes
        id: check_changes
        run: |
          git status
          if [[ -n $(git status -s) ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push if there are changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git add .
          git commit -m "Auto-update KernelSU-Next submodule to latest next branch"
          git push origin HEAD:latest